services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://devopsuser:devopspass@db:5432/devopsdb
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devopsuser
      POSTGRES_PASSWORD: devopspass
    ports:
      - "5432:5432"